version: "3"
services:
  postgres:
    image: "postgres:12"
    env_file: .env
    logging:
      options:
        max-size: 100m
        max-file: "3"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # main django web service
  django:
    build:
      context: ../..
      dockerfile: Ctl/docker/Dockerfile
    command: "runserver 0.0.0.0:8000"
    env_file: .env
    ports:
      - "127.0.0.1:${DJANGO_PORT:-8000}:8000"
    logging:
      options:
        max-size: 100m
        max-file: "3"
    volumes:
      - ../../src:/srv/service/main:Z
    depends_on:
      - postgres

  # separate django task service
  tasks:
    build:
      context: ../..
      dockerfile: Ctl/docker/Dockerfile.tasks
    command: "fullctl_poll_tasks --workers 4"
    env_file: .env
    logging:
      options:
        max-size: 100m
        max-file: "3"
    volumes:
      - ../../src:/srv/service/main:Z
    depends_on:
      - postgres


volumes:
  postgres_data:
