# Generated by Django 3.2.9 on 2022-04-04 17:07

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prefix_meta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IP2Location",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.request",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="data",
            managers=[],
        ),
    ]
