# Generated by Django 3.2.9 on 2022-04-05 10:39

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0019_default_org"),
        ("prefix_meta", "0002_auto_20220404_1707"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationUpdateTask",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="request",
            managers=[],
        ),
    ]
