# Generated by Django 3.2.15 on 2023-02-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prefix_meta", "0005_move_existing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="date",
            field=models.DateTimeField(help_text="Data validity date"),
        ),
    ]
