# Generated by Django 3.2.15 on 2023-02-22 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prefix_meta", "0007_auto_20230222_1629"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="request",
            unique_together=set(),
        ),
    ]
