# Generated by Django 3.2.15 on 2023-02-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prefix_meta", "0008_alter_request_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
