# Generated by Django 3.2.15 on 2023-02-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prefix_meta", "0009_request_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="type",
            field=models.CharField(default="info", max_length=255),
        ),
    ]
