# Generated by Django 3.2.15 on 2023-02-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prefix_meta", "0010_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="date",
            field=models.DateTimeField(help_text="Data validity start date"),
        ),
    ]
