# Generated by Django 3.2.15 on 2023-02-24 11:35

import django.db.models.deletion
import django.db.models.expressions
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prefix_meta", "0011_alter_data_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", netfields.fields.CidrAddressField(max_length=43)),
                (
                    "meta_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subnets",
                        to="prefix_meta.data",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subnet match",
                "verbose_name_plural": "Subnet matches",
                "db_table": "prefix_meta_data_subnet",
            },
        ),
        migrations.AddIndex(
            model_name="datasubnet",
            index=models.Index(
                django.db.models.expressions.F("prefix"), name="subnet_prefix_idx"
            ),
        ),
    ]
