# Generated by Django 3.2.15 on 2023-02-24 12:52

from django.db import migrations


def forwards(apps, schema_editor):
    Data = apps.get_model("prefix_meta", "Data")
    Data.objects.filter(source_name="ip2location").update(type="location")


def backwards(apps, schema_editor):
    Data = apps.get_model("prefix_meta", "Data")
    Data.objects.filter(source_name="ip2location").update(type="info")


class Migration(migrations.Migration):
    dependencies = [
        ("prefix_meta", "0012_auto_20230224_1135"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
