# Generated by Django 3.2.15 on 2023-02-26 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prefix_meta", "0013_location_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RdapData",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.data",),
        ),
        migrations.CreateModel(
            name="RdapRequest",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.request",),
        ),
        migrations.CreateModel(
            name="RipestatData",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.data",),
        ),
        migrations.CreateModel(
            name="RipestatRequest",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.request",),
        ),
        migrations.CreateModel(
            name="BgpUpdates",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.ripestatrequest",),
        ),
        migrations.CreateModel(
            name="BgpUpdatesData",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.ripestatdata",),
        ),
        migrations.CreateModel(
            name="HistoricalWhois",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.ripestatrequest",),
        ),
        migrations.CreateModel(
            name="HistoricalWhoisData",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.ripestatdata",),
        ),
        migrations.CreateModel(
            name="RIR",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.ripestatrequest",),
        ),
        migrations.CreateModel(
            name="RIRData",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.ripestatdata",),
        ),
        migrations.CreateModel(
            name="RIRStatsCountry",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.ripestatrequest",),
        ),
        migrations.CreateModel(
            name="RIRStatsCountryData",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.ripestatdata",),
        ),
        migrations.CreateModel(
            name="RoutingStatus",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.ripestatrequest",),
        ),
        migrations.CreateModel(
            name="RoutingStatusData",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("prefix_meta.ripestatdata",),
        ),
    ]
