# Generated by Django 4.2.10 on 2024-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prefix_meta", "0016_auto_20230310_1315"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="data",
            name="prefix_type_idx",
        ),
        migrations.AddIndex(
            model_name="data",
            index=models.Index(
                fields=["prefix", "type", "date"], name="prefix_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasubnet",
            index=models.Index(
                models.F("meta_data_id"), name="subnet_meta_data_id_idx"
            ),
        ),
    ]
