# Generated by Django 3.2.9 on 2021-11-22 12:24

import netfields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_prefixctl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prefix",
            name="prefix",
            field=netfields.fields.CidrAddressField(max_length=43),
        ),
    ]
