# Generated by Django 3.2.9 on 2022-01-07 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0018_task_schedule"),
        ("django_prefixctl", "0002_net_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prefixmonitor",
            options={
                "verbose_name": "Prefix Monitor",
                "verbose_name_plural": "Prefix Monitors",
            },
        ),
        migrations.AddField(
            model_name="prefixmonitor",
            name="task_schedule",
            field=models.OneToOneField(
                blank=True,
                help_text="The task schedule for this monitor",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_fullctl.taskschedule",
            ),
        ),
    ]
