# Generated by Django 3.2.9 on 2022-01-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_prefixctl", "0003_auto_20220107_1418"),
    ]

    operations = [
        migrations.AddField(
            model_name="asnmonitor",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Primary alert notification email",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prefixmonitor",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Primary alert notification email",
                max_length=254,
                null=True,
            ),
        ),
    ]
