# Generated by Django 3.2.9 on 2022-03-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_prefixctl", "0004_auto_20220110_1429"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prefixmonitor",
            options={
                "verbose_name": "Prefix ASN Monitor",
                "verbose_name_plural": "Prefix ASN Monitors",
            },
        ),
        migrations.AddField(
            model_name="prefixset",
            name="ux_keep_list_open",
            field=models.BooleanField(
                default=False, help_text="UX Preference: Keep prefix list expanded"
            ),
        ),
    ]
