# Generated by Django 3.2.12 on 2022-07-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0019_default_org"),
        ("django_prefixctl", "0005_auto_20220307_0752"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asn",
            old_name="asnset",
            new_name="asn_set",
        ),
        migrations.RenameField(
            model_name="asnmonitor",
            old_name="asnset",
            new_name="asn_set",
        ),
        migrations.RenameField(
            model_name="prefixmonitor",
            old_name="asnset_origin",
            new_name="asn_set_origin",
        ),
        migrations.RenameField(
            model_name="prefixmonitor",
            old_name="asnset_upstream",
            new_name="asn_set_upstream",
        ),
        migrations.AlterField(
            model_name="asnset",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asn_set_set",
                to="django_fullctl.instance",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asn",
            unique_together={("asn_set", "asn")},
        ),
    ]
