# Generated by Django 3.2.12 on 2022-07-12 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0019_default_org"),
        ("django_prefixctl", "0007_reftag_prefix_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prefix",
            name="prefix_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prefix_set",
                to="django_prefixctl.prefixset",
            ),
        ),
        migrations.AlterField(
            model_name="prefixmonitor",
            name="asn_set_origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prefix_monitor_origin_set",
                to="django_prefixctl.asnset",
            ),
        ),
        migrations.AlterField(
            model_name="prefixmonitor",
            name="asn_set_upstream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prefix_monitor_upstream_set",
                to="django_prefixctl.asnset",
            ),
        ),
        migrations.AlterField(
            model_name="prefixmonitor",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prefix_monitor_set",
                to="django_fullctl.instance",
            ),
        ),
        migrations.AlterField(
            model_name="prefixmonitor",
            name="prefix_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prefix_monitor_set",
                to="django_prefixctl.prefixset",
            ),
        ),
        migrations.AlterModelTable(
            name="prefix",
            table="prefixctl_prefix",
        ),
        migrations.AlterModelTable(
            name="prefixmonitor",
            table="prefixctl_prefix_monitor",
        ),
        migrations.AlterModelTable(
            name="prefixsettask",
            table="prefixctl_prefix_set_task",
        ),
    ]
