# Generated by Django 3.2.17 on 2023-03-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0026_auto_20230131_1405"),
        ("django_prefixctl", "0010_reftag_alert_log_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asnset",
            name="instance",
            field=models.ForeignKey(
                help_text="Environment instance id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asn_set_set",
                to="django_fullctl.instance",
            ),
        ),
        migrations.AlterField(
            model_name="prefixset",
            name="instance",
            field=models.ForeignKey(
                help_text="Environment instance id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prefix_set_set",
                to="django_fullctl.instance",
            ),
        ),
    ]
