# Generated by Django 3.2.23 on 2024-01-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0032_auto_20230719_1049"),
        ("django_prefixctl", "0011_auto_20230301_1445"),
    ]

    operations = [
        migrations.AddField(
            model_name="asnmonitor",
            name="task_schedule",
            field=models.OneToOneField(
                blank=True,
                help_text="The task schedule for this monitor",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_fullctl.taskschedule",
            ),
        ),
    ]
