# Generated by Django 3.2.23 on 2024-01-11 17:01

import django.db.models.deletion
import django.db.models.manager
import django_handleref.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0032_auto_20230719_1049"),
        ("django_prefixctl", "0012_asnmonitor_task_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrefixSetIRRImporter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created",
                    django_handleref.models.CreatedDateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    django_handleref.models.UpdatedDateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("pending", "Pending"),
                            ("deactivated", "Deactivated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary alert notification email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefix_set_irr_importers",
                        to="django_fullctl.instance",
                    ),
                ),
                (
                    "prefix_set",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefix_set_irr_importer",
                        to="django_prefixctl.prefixset",
                    ),
                ),
                (
                    "task_schedule",
                    models.OneToOneField(
                        blank=True,
                        help_text="The task schedule for the irr importer",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_fullctl.taskschedule",
                    ),
                ),
            ],
            options={
                "db_table": "prefixctl_prefix_set_irr_importer",
            },
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name="PrefixSetTask",
        ),
    ]
