# Generated by Django 4.2.10 on 2024-02-12 22:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_prefixctl",
            "0014_irrimporttask_alter_asnset_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="IRRImportTask",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
    ]
