# Generated by Django 4.2.10 on 2024-02-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_prefixctl", "0015_irrimporttask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asnset",
            name="slug",
            field=models.SlugField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="prefixset",
            name="slug",
            field=models.SlugField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
