# Generated by Django 4.2.11 on 2024-04-24 20:51

from django.db import migrations

def delete_prefix_monitor_tasks(apps, schema_editor):
    Task = apps.get_model('django_fullctl', 'Task')
    TaskSchedule = apps.get_model('django_fullctl', 'TaskSchedule')

    Task.handleref.filter(op="prefix_monitor_task").delete()

    for ts in TaskSchedule.handleref.all():
        if "tasks" in ts.task_config:
            for task in ts.task_config["tasks"]:
                if task.get("op") == "prefix_monitor_task":
                    ts.delete()
                    break


class Migration(migrations.Migration):

    dependencies = [
        ("django_prefixctl", "0017_remove_prefixmonitor_asn_set_origin_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_prefix_monitor_tasks, migrations.RunPython.noop),
    ]
