# Generated by Django 4.2.13 on 2024-07-15 20:32

from django.db import migrations, models
import fullctl.django.inet.validators


class Migration(migrations.Migration):

    dependencies = [
        ("django_prefixctl", "0018_cleanup_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prefixset",
            name="irr_as_set",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="import prefixes for AS-SET",
                max_length=255,
                null=True,
                validators=[fullctl.django.inet.validators.validate_as_set],
            ),
        ),
    ]
